site_name: Ariadne 文档
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/file-document-multiple-outline
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 黑暗模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 明亮模式

repo_url: https://github.com/GraiaProject/Ariadne
repo_name: GraiaProject/Ariadne
copyright: Copyright &copy; 2021 Graia Project.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GraiaProject
      name: Github 组织
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=VXp6plBD
      name: QQ 群
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition # 提示块
  - footnotes # 脚注
  - meta # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret # 下划线上标
  - pymdownx.tilde # 删除线下标
  - pymdownx.critic # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details # 提示块可折叠
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.mark # 文本高亮
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.superfences # 代码嵌套在列表里
  - codehilite: # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc: # 锚点
      permalink: true
  - pymdownx.arithmatex # 数学公式
  - pymdownx.betterem: # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.emoji: # 表情
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink # 自动识别超链接
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true

nav:
  - "index.md"
  - "基础":
      - "basic/quickstart.md"
      - "basic/configuration.md"
      - "basic/application.md"
      - "basic/msg-chain.md"
      - "basic/log.md"
  - "进阶":
      - "advance/msg-chain.md"
      - "advance/base-parser.md"
      - "advance/literature.md"
      - "advance/twilight.md"
      - "advance/interrupt.md"
      - Broadcast 介绍 (外部): https://autumn-psi.vercel.app/
  - "配套设施":
      - "suite/scheduler.md"
      - "suite/saya.md"
  - "迁移":
      - "porting/guide.md"
      - "porting/cheatsheet.md"
  - "faq.md"
  - "TODO.md"
  - "credits.md"
  - GitHub 仓库: https://github.com/GraiaProject/Ariadne
